package com.jiawei.mybatis.pojo;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.dept_id
     *
     * @mbg.generated Tue Nov 29 21:21:28 EST 2022
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.name
     *
     * @mbg.generated Tue Nov 29 21:21:28 EST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.manager_id
     *
     * @mbg.generated Tue Nov 29 21:21:28 EST 2022
     */
    private Integer managerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.dept_id
     *
     * @return the value of Department.dept_id
     *
     * @mbg.generated Tue Nov 29 21:21:28 EST 2022
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.dept_id
     *
     * @param deptId the value for Department.dept_id
     *
     * @mbg.generated Tue Nov 29 21:21:28 EST 2022
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.name
     *
     * @return the value of Department.name
     *
     * @mbg.generated Tue Nov 29 21:21:28 EST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.name
     *
     * @param name the value for Department.name
     *
     * @mbg.generated Tue Nov 29 21:21:28 EST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Department.manager_id
     *
     * @return the value of Department.manager_id
     *
     * @mbg.generated Tue Nov 29 21:21:28 EST 2022
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Department.manager_id
     *
     * @param managerId the value for Department.manager_id
     *
     * @mbg.generated Tue Nov 29 21:21:28 EST 2022
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }
}